- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.10.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.10.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.1?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.2
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.2?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.3
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.3?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.4
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.4?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.5.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.5.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.6.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.6.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.7.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.7.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.8.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.8.0?classifier=sources
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.9.0
- pkg:maven/io.prometheus.cloudwatch/cloudwatch_exporter@0.9.0?classifier=sources
