- pkg:maven/org.apache.solr/solr-prometheus-exporter@7.3.0
- pkg:maven/org.apache.solr/solr-prometheus-exporter@7.3.0?classifier=sources
- pkg:maven/org.apache.solr/solr-prometheus-exporter@7.3.1
- pkg:maven/org.apache.solr/solr-prometheus-exporter@7.3.1?classifier=sources
