- pkg:maven/io.prometheus/simpleclient_logback@0.0.10
- pkg:maven/io.prometheus/simpleclient_logback@0.0.10?classifier=sources
- pkg:maven/io.prometheus/simpleclient_logback@0.0.11
- pkg:maven/io.prometheus/simpleclient_logback@0.0.11?classifier=sources
- pkg:maven/io.prometheus/simpleclient_logback@0.0.9
- pkg:maven/io.prometheus/simpleclient_logback@0.0.9?classifier=sources
