- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.4.0
- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.4.0?classifier=sources
- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.5.0
- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.5.0?classifier=sources
- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.6.0
- pkg:maven/org.apache.karaf.decanter.collector/org.apache.karaf.decanter.collector.prometheus@2.6.0?classifier=sources
