- pkg:maven/io.smallrye.config.examples/configmap@1.9.0
- pkg:maven/io.smallrye.config.examples/configmap@1.9.0?classifier=sources
- pkg:maven/io.smallrye.config.examples/configmap@1.9.1
- pkg:maven/io.smallrye.config.examples/configmap@1.9.1?classifier=sources
- pkg:maven/io.smallrye.config.examples/configmap@1.9.2
- pkg:maven/io.smallrye.config.examples/configmap@1.9.2?classifier=sources
- pkg:maven/io.smallrye.config.examples/configmap@1.9.3
- pkg:maven/io.smallrye.config.examples/configmap@1.9.3?classifier=sources
- pkg:maven/io.smallrye.config.examples/configmap@2.0.0-RC1
- pkg:maven/io.smallrye.config.examples/configmap@2.0.0-RC1?classifier=sources
