- pkg:maven/com.alibaba.csp/sentinel-prometheus-metric-exporter@1.8.7
- pkg:maven/com.alibaba.csp/sentinel-prometheus-metric-exporter@1.8.7?classifier=sources
- pkg:maven/com.alibaba.csp/sentinel-prometheus-metric-exporter@1.8.8
- pkg:maven/com.alibaba.csp/sentinel-prometheus-metric-exporter@1.8.8?classifier=sources
