- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.0
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.0?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.1
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.1?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.2
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.2?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.3
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.3?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.4
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.4?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.5
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.5?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.6
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.6?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.7
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.0.7?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.1.0
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.1.0?classifier=sources
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.1.1
- pkg:maven/no.digipost/digipost-micrometer-prometheus@1.1.1?classifier=sources
