- pkg:maven/at.ac.ait.lablink/config@0.1.0
- pkg:maven/at.ac.ait.lablink/config@0.1.0?classifier=sources
- pkg:maven/at.ac.ait.lablink/config@0.1.1
- pkg:maven/at.ac.ait.lablink/config@0.1.1?classifier=sources
