- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@1.0.0
- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@1.0.0?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@2.0.0-RC1
- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@2.0.0-RC1?classifier=sources
- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@2.0.0-RC2
- pkg:maven/com.permutive/prometheus4cats-contrib-fs2-kafka_2.12@2.0.0-RC2?classifier=sources
