- pkg:maven/de.hamstersimulator.objectsfirst/config@4.0.0
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.0.0?classifier=sources
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.1.0
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.1.0?classifier=sources
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.1.1
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.1.1?classifier=sources
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.2.0
- pkg:maven/de.hamstersimulator.objectsfirst/config@4.2.0?classifier=sources
