- pkg:maven/com.marvinformatics/docker-compose-maven-plugin@5.0.0
- pkg:maven/com.marvinformatics/docker-compose-maven-plugin@5.0.0?classifier=sources
- pkg:maven/com.marvinformatics/docker-compose-maven-plugin@6.0?classifier=sources
