- pkg:maven/io.prometheus/example_application@0.11.0
- pkg:maven/io.prometheus/example_application@0.11.0?classifier=sources
- pkg:maven/io.prometheus/example_application@0.12.0
- pkg:maven/io.prometheus/example_application@0.12.0?classifier=sources
